# Generated by Django 5.2.4 on 2025-07-03 20:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('upc_ean', models.CharField(blank=True, help_text='Universal Product Code / European Article Number', max_length=20, null=True, unique=True)),
                ('product_name', models.CharField(help_text='Name of the product', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, help_text="Manufacturer's Recommended Price per unit", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=3, help_text='Weight of a single unit (e.g., in kg)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measure', models.CharField(blank=True, help_text='Unit type (e.g., kg, dozen, pouch)', max_length=20)),
                ('shelf_life_days', models.IntegerField(help_text='Standard shelf life in days from production', validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_requirements', models.CharField(blank=True, help_text='Storage requirements (e.g., Refrigerated)', max_length=255)),
                ('is_perishable', models.BooleanField(default=True, help_text='Indicates if product is perishable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer_batch_number', models.CharField(help_text='Batch number from manufacturer', max_length=100)),
                ('production_date', models.DateField(help_text='Date the batch was produced')),
                ('expiration_date', models.DateField(help_text='Date the batch expires')),
                ('initial_quantity', models.DecimalField(decimal_places=2, help_text='Quantity received from manufacturer', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.DecimalField(decimal_places=2, help_text='Current available quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_stock', 'In Stock'), ('dispatched', 'Dispatched'), ('expired', 'Expired'), ('recalled', 'Recalled')], default='received', max_length=20)),
                ('manufacturing_location', models.CharField(blank=True, help_text='Location where batch was manufactured', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['-production_date'],
                'unique_together': {('product', 'manufacturer_batch_number')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Physical location of inventory', max_length=255)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, help_text='Current quantity at this location', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity threshold for replenishment alert', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.batch')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['location', 'batch__expiration_date'],
                'unique_together': {('batch', 'location')},
            },
        ),
    ]
